version: 2

models:
  - name: fact_page_views
    description: contains all page view events
    columns:
      - name: event_guid
        tests: 
          - unique
          - not_null
      - name: session_guid
        tests:
          - not_null
      - name: user_guid
      - name: page_url
        tests: 
          - not_null
      - name: created_at_utc
        tests: 
          - not_null
      - name: product_guid
      - name: product_name
      - name: price
        tests: 
          - positive_values
      - name: inventory_count
        tests: 
          - not_null
  - name: fact_sessions_events
    description: for each session, whether it had an event of each type
    columns: 
      - name: session_guid
        tests: 
          - unique
          - not_null
      - name: has_page_view
      - name: has_add_to_cart
      - name: has_checkout
      - name: has_package_shipped
  - name: funnel_sessions
    description: for each session, whether it is in each funnel level
    columns: 
      - name: session_guid
        tests: 
          - unique
          - not_null
      - name: level_page_view
      - name: level_add_to_cart
      - name: level_checkout
