version: 2

models:
  - name: fact_page_views
    description: contains all page view events
    columns:
      - name: event_guid
        tests: 
          - unique
          - not_null
      - name: session_guid
        tests:
          - not_null
      - name: user_guid
      - name: page_url
        tests: 
          - not_null
      - name: created_at_utc
        tests: 
          - not_null
      - name: product_guid
      - name: product_name
      - name: price
        tests: 
          - positive_values
      - name: inventory_count
        tests: 
          - not_null